basePath: /weflow
definitions:
  base.Response:
    properties:
      code:
        description: 0:成功，其他：失败
        type: integer
      data:
        description: 数据
      msg:
        description: 错误信息
        type: string
    type: object
  bo.InstTaskResult:
    properties:
      createTime:
        description: 创建时间 yyyy-MM-dd HH:mm:ss:SSS
        type: string
      createUserID:
        description: 创建人id
        type: string
      createUserName:
        description: 创建人名称
        type: string
      endTime:
        description: 结束时间 yyyy-MM-dd HH:mm:ss:SSS
        type: string
      formDefID:
        description: 表单定义id
        type: string
      id:
        description: 唯一id
        type: integer
      instTaskID:
        description: 实例任务id
        type: string
      modelID:
        description: 模板id
        type: string
      processDefID:
        description: 流程定义id
        type: string
      remark:
        description: 描述
        type: string
      startTime:
        description: 发起时间 yyyy-MM-dd HH:mm:ss:SSS
        type: string
      status:
        description: 任务状态【1：创建中(草稿)；2：进行中； 3：终止； 4：完成； 5：挂起；6：回退】
        type: integer
      taskName:
        description: 实例任务名称
        type: string
      updateTime:
        description: 更新时间 yyyy-MM-dd HH:mm:ss:SSS
        type: string
      updateUserID:
        description: 更新人id
        type: string
      updateUserName:
        description: 更新人名称
        type: string
      versionID:
        description: 版本id
        type: string
    type: object
  bo.ModelDetailResult:
    properties:
      createTime:
        description: 创建时间 yyyy-MM-dd HH:mm:ss:SSS
        type: string
      createUser:
        description: 创建人
        type: string
      formDefID:
        description: 表单定义id
        type: string
      iconURL:
        description: icon图标地址
        type: string
      id:
        description: 唯一id
        type: integer
      modelGroupID:
        description: 模版组id
        type: string
      modelID:
        description: 模板id
        type: string
      modelTitle:
        description: 模板标题
        type: string
      processDefID:
        description: 流程定义id
        type: string
      remark:
        description: 描述
        type: string
      status:
        description: 模板状态【1：草稿；2：发布；3：停用】默认草稿
        type: integer
      updateTime:
        description: 更新时间 yyyy-MM-dd HH:mm:ss:SSS
        type: string
      updateUser:
        description: 更新人
        type: string
    type: object
  bo.ModelGroupResult:
    properties:
      createTime:
        description: 创建时间 yyyy-MM-dd HH:mm:ss:SSS
        type: string
      createUser:
        description: 创建人
        type: string
      groupID:
        description: 组id
        type: string
      groupName:
        description: 组名称
        type: string
      id:
        description: 唯一id
        type: integer
      remark:
        description: 描述
        type: string
      updateTime:
        description: 更新时间 yyyy-MM-dd HH:mm:ss:SSS
        type: string
      updateUser:
        description: 更新人
        type: string
    type: object
  bo.UserTaskResult:
    properties:
      createUserID:
        description: 创建人id
        type: string
      createUserName:
        description: 创建人名称
        type: string
      endTime:
        description: 结束时间
        type: string
      instStatus:
        description: 任务状态【1：创建中(草稿)；2：进行中； 3：终止； 4：完成； 5：挂起；6：回退】
        type: integer
      instTaskID:
        description: 实例任务id
        type: string
      nodeID:
        description: 节点id
        type: string
      nodeModel:
        description: 节点模型【1：开始节点；2：审批节点；3：办理节点；4：抄送节点；5：自定义节点；6：条件节点；7：分支节点；8：汇聚节点；9：结束节点】
        type: integer
      nodeName:
        description: 节点名称
        type: string
      nodeTaskID:
        description: 节点任务id
        type: string
      parentID:
        description: 父节点id
        type: string
      startTime:
        description: 发起时间
        type: string
      taskName:
        description: 实例任务名称
        type: string
      userTaskID:
        description: 处理人任务id
        type: string
    type: object
  bo.UserTaskTodoResult:
    properties:
      createUserID:
        description: 创建人id
        type: string
      createUserName:
        description: 创建人名称
        type: string
      endTime:
        description: 结束时间 yyyy-MM-dd HH:mm:ss:SSS
        type: string
      instStatus:
        description: 任务状态【1：创建中(草稿)；2：进行中； 3：终止； 4：完成； 5：挂起；6：回退】
        type: integer
      instTaskID:
        description: 实例任务id
        type: string
      nodeID:
        description: 节点id
        type: string
      nodeModel:
        description: 节点模型【1：开始节点；2：审批节点；3：办理节点；4：抄送节点；5：自定义节点；6：条件节点；7：分支节点；8：汇聚节点；9：结束节点】
        type: integer
      nodeName:
        description: 节点名称
        type: string
      nodeTaskID:
        description: 节点任务id
        type: string
      parentID:
        description: 父节点id
        type: string
      startTime:
        description: 发起时间 yyyy-MM-dd HH:mm:ss:SSS
        type: string
      taskName:
        description: 实例任务名称
        type: string
      userTaskID:
        description: 处理人任务id
        type: string
    type: object
  vo.ModelGroupAddVO:
    properties:
      groupName:
        description: 组名称
        type: string
      remark:
        description: 描述
        type: string
    type: object
  vo.ModelGroupDelVO:
    properties:
      groupID:
        description: 组id
        type: string
    type: object
  vo.ModelGroupEditVO:
    properties:
      groupID:
        description: 组id
        type: string
      groupName:
        description: 组名称
        type: string
      remark:
        description: 描述
        type: string
    type: object
host: localhost:8080
info:
  contact:
    name: hertz-contrib
    url: https://github.com/hertz-contrib
  description: weflow swagger api documention.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: weflow
  version: "1.0"
paths:
  /comm/snowflake:
    get:
      consumes:
      - application/json
      description: 获取雪花算法唯一ID
      operationId: GetSnowflake
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/base.Response'
            - properties:
                data:
                  type: string
              type: object
      summary: 获取雪花算法唯一ID
      tags:
      - 公共
  /insttask/del:
    post:
      consumes:
      - application/json
      description: 删除实例任务
      produces:
      - application/json
      responses:
        "200":
          description: 返回结果
          schema:
            $ref: '#/definitions/base.Response'
      summary: 删除实例任务
      tags:
      - 实例任务
  /insttask/initiated:
    get:
      consumes:
      - application/json
      description: 获取发起的实例任务列表（已发起）
      parameters:
      - description: 提交审批时间-结束 yyyy-MM-dd HH:mm:ss:SSS
        example: 提交审批时间
        in: query
        name: createTimeEnd
        type: string
      - description: 提交审批时间-开始 yyyy-MM-dd HH:mm:ss:SSS
        example: 提交审批时间
        in: query
        name: createTimeStart
        type: string
      - description: 完成审批时间-结束 yyyy-MM-dd HH:mm:ss:SSS
        example: 完成审批时间
        in: query
        name: finishTimeEnd
        type: string
      - description: 完成审批时间-开始 yyyy-MM-dd HH:mm:ss:SSS
        example: 完成审批时间
        in: query
        name: finishTimeStart
        type: string
      - description: 任务状态
        example: 1
        in: query
        name: instStatus
        type: integer
      - description: 模板ID
        example: 模板ID
        in: query
        name: modelID
        type: string
      - description: 页码
        example: 1
        in: query
        name: pageNum
        type: integer
      - description: 每页条数
        example: 30
        in: query
        name: pageSize
        type: integer
      - description: 任务名称
        example: 任务名称
        in: query
        name: taskName
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 返回结果
          schema:
            allOf:
            - $ref: '#/definitions/base.Response'
            - properties:
                data:
                  $ref: '#/definitions/bo.InstTaskResult'
              type: object
      summary: 获取发起的实例任务列表（已发起）
      tags:
      - 实例任务
  /insttask/resume:
    post:
      consumes:
      - application/json
      description: 恢复实例任务
      produces:
      - application/json
      responses:
        "200":
          description: 返回结果
          schema:
            $ref: '#/definitions/base.Response'
      summary: 恢复实例任务
      tags:
      - 实例任务
  /insttask/start:
    post:
      consumes:
      - application/json
      description: 发起实例任务
      produces:
      - application/json
      responses:
        "200":
          description: 返回结果
          schema:
            $ref: '#/definitions/base.Response'
      summary: 发起实例任务
      tags:
      - 实例任务
  /insttask/stop:
    post:
      consumes:
      - application/json
      description: 终止实例任务
      produces:
      - application/json
      responses:
        "200":
          description: 返回结果
          schema:
            $ref: '#/definitions/base.Response'
      summary: 终止实例任务
      tags:
      - 实例任务
  /insttask/suspend:
    post:
      consumes:
      - application/json
      description: 挂起实例任务
      produces:
      - application/json
      responses:
        "200":
          description: 返回结果
          schema:
            $ref: '#/definitions/base.Response'
      summary: 挂起实例任务
      tags:
      - 实例任务
  /model/group/add:
    post:
      consumes:
      - application/json
      description: 添加模板组
      parameters:
      - description: 请求参数
        in: body
        name: ModelGroupAddVO
        required: true
        schema:
          $ref: '#/definitions/vo.ModelGroupAddVO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/base.Response'
      summary: 添加模板组
      tags:
      - 模板
  /model/group/del:
    post:
      consumes:
      - application/json
      description: 删除模板组
      parameters:
      - description: 请求参数
        in: body
        name: ModelGroupDelVO
        required: true
        schema:
          $ref: '#/definitions/vo.ModelGroupDelVO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/base.Response'
      summary: 删除模板组
      tags:
      - 模板
  /model/group/edit:
    post:
      consumes:
      - application/json
      description: 编辑模板组
      parameters:
      - description: 请求参数
        in: body
        name: ModelGroupEditVO
        required: true
        schema:
          $ref: '#/definitions/vo.ModelGroupEditVO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/base.Response'
      summary: 编辑模板组
      tags:
      - 模板
  /model/group/list:
    get:
      consumes:
      - application/json
      description: 查询获取模板组列表
      produces:
      - application/json
      responses:
        "200":
          description: 返回结果
          schema:
            allOf:
            - $ref: '#/definitions/base.Response'
            - properties:
                data:
                  $ref: '#/definitions/bo.ModelGroupResult'
              type: object
      summary: 查询获取模板组列表
      tags:
      - 模板
  /model/list:
    get:
      consumes:
      - application/json
      description: 获取模板列表
      produces:
      - application/json
      responses:
        "200":
          description: 返回结果
          schema:
            allOf:
            - $ref: '#/definitions/base.Response'
            - properties:
                data:
                  $ref: '#/definitions/bo.ModelDetailResult'
              type: object
      summary: 获取模板列表
      tags:
      - 模板
  /model/page:
    get:
      consumes:
      - application/json
      description: 分页获取模板列表
      produces:
      - application/json
      responses:
        "200":
          description: 返回结果
          schema:
            allOf:
            - $ref: '#/definitions/base.Response'
            - properties:
                data:
                  $ref: '#/definitions/bo.ModelDetailResult'
              type: object
      summary: 分页获取模板列表
      tags:
      - 模板
  /usertask/agree:
    post:
      consumes:
      - application/json
      description: 同意用户任务
      produces:
      - application/json
      responses:
        "200":
          description: 返回结果
          schema:
            $ref: '#/definitions/base.Response'
      summary: 同意用户任务
      tags:
      - 用户任务
  /usertask/disagree:
    post:
      consumes:
      - application/json
      description: 不同意用户任务
      produces:
      - application/json
      responses:
        "200":
          description: 返回结果
          schema:
            $ref: '#/definitions/base.Response'
      summary: 不同意用户任务
      tags:
      - 用户任务
  /usertask/done:
    get:
      consumes:
      - application/json
      description: 获取已办用户任务列表（已处理）
      parameters:
      - description: 提交审批时间-结束 yyyy-MM-dd HH:mm:ss:SSS
        example: 提交审批时间
        in: query
        name: createTimeEnd
        type: string
      - description: 提交审批时间-开始 yyyy-MM-dd HH:mm:ss:SSS
        example: 提交审批时间
        in: query
        name: createTimeStart
        type: string
      - description: 创建人id
        example: 创建人id
        in: query
        name: createUserID
        type: string
      - description: 完成审批时间-结束 yyyy-MM-dd HH:mm:ss:SSS
        example: 完成审批时间
        in: query
        name: finishTimeEnd
        type: string
      - description: 完成审批时间-开始 yyyy-MM-dd HH:mm:ss:SSS
        example: 完成审批时间
        in: query
        name: finishTimeStart
        type: string
      - description: 任务状态
        example: 1
        in: query
        name: instStatus
        type: integer
      - description: 模板ID
        example: 模板ID
        in: query
        name: modelID
        type: string
      - description: 页码
        example: 1
        in: query
        name: pageNum
        type: integer
      - description: 每页条数
        example: 30
        in: query
        name: pageSize
        type: integer
      - description: 任务名称
        example: 任务名称
        in: query
        name: taskName
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 返回结果
          schema:
            allOf:
            - $ref: '#/definitions/base.Response'
            - properties:
                data:
                  $ref: '#/definitions/bo.UserTaskResult'
              type: object
      summary: 获取已办用户任务列表（已处理）
      tags:
      - 用户任务
  /usertask/received:
    get:
      consumes:
      - application/json
      description: 获取用户任务列表（我收到的）
      parameters:
      - description: 提交审批时间-结束 yyyy-MM-dd HH:mm:ss:SSS
        example: 提交审批时间
        in: query
        name: createTimeEnd
        type: string
      - description: 提交审批时间-开始 yyyy-MM-dd HH:mm:ss:SSS
        example: 提交审批时间
        in: query
        name: createTimeStart
        type: string
      - description: 创建人id
        example: 创建人id
        in: query
        name: createUserID
        type: string
      - description: 完成审批时间-结束 yyyy-MM-dd HH:mm:ss:SSS
        example: 完成审批时间
        in: query
        name: finishTimeEnd
        type: string
      - description: 完成审批时间-开始 yyyy-MM-dd HH:mm:ss:SSS
        example: 完成审批时间
        in: query
        name: finishTimeStart
        type: string
      - description: 任务状态
        example: 1
        in: query
        name: instStatus
        type: integer
      - description: 模板ID
        example: 模板ID
        in: query
        name: modelID
        type: string
      - description: 页码
        example: 1
        in: query
        name: pageNum
        type: integer
      - description: 每页条数
        example: 30
        in: query
        name: pageSize
        type: integer
      - description: 任务名称
        example: 任务名称
        in: query
        name: taskName
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 返回结果
          schema:
            allOf:
            - $ref: '#/definitions/base.Response'
            - properties:
                data:
                  $ref: '#/definitions/bo.UserTaskResult'
              type: object
      summary: 获取用户任务列表（我收到的）
      tags:
      - 用户任务
  /usertask/save:
    post:
      consumes:
      - application/json
      description: 保存用户任务
      produces:
      - application/json
      responses:
        "200":
          description: 返回结果
          schema:
            $ref: '#/definitions/base.Response'
      summary: 保存用户任务
      tags:
      - 用户任务
  /usertask/todo:
    get:
      consumes:
      - application/json
      description: 获取待办用户任务列表（待处理）
      parameters:
      - description: 提交审批时间-结束 yyyy-MM-dd HH:mm:ss:SSS
        example: 提交审批时间
        in: query
        name: createTimeEnd
        type: string
      - description: 提交审批时间-开始 yyyy-MM-dd HH:mm:ss:SSS
        example: 提交审批时间
        in: query
        name: createTimeStart
        type: string
      - description: 创建人id
        example: 创建人id
        in: query
        name: createUserID
        type: string
      - description: 完成审批时间-结束 yyyy-MM-dd HH:mm:ss:SSS
        example: 完成审批时间
        in: query
        name: finishTimeEnd
        type: string
      - description: 完成审批时间-开始 yyyy-MM-dd HH:mm:ss:SSS
        example: 完成审批时间
        in: query
        name: finishTimeStart
        type: string
      - description: 任务状态
        example: 1
        in: query
        name: instStatus
        type: integer
      - description: 模板ID
        example: 模板ID
        in: query
        name: modelID
        type: string
      - description: 页码
        example: 1
        in: query
        name: pageNum
        type: integer
      - description: 每页条数
        example: 30
        in: query
        name: pageSize
        type: integer
      - description: 任务名称
        example: 任务名称
        in: query
        name: taskName
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 返回结果
          schema:
            allOf:
            - $ref: '#/definitions/base.Response'
            - properties:
                data:
                  $ref: '#/definitions/bo.UserTaskTodoResult'
              type: object
      summary: 获取待办用户任务列表（待处理）
      tags:
      - 用户任务
schemes:
- http
swagger: "2.0"
